version: '3.8'

services:
  geodistance:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    #    command: sh -c "env && java -jar app.jar"
    environment:
      SPRING_PROFILES_ACTIVE: dev

      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: distcalc_dev
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

      YANDEX_API_KEY: a95f5d4d-151b-42d9-8519-7aef29a5a5c1
      DADATA_API_KEY: 3ae49eb03d50473ad14419fe4dbd953a99dff432
      DADATA_TOKEN: 3ae49eb03d50473ad14419fe4dbd953a99dff432
      DADATA_SECRET: 37b92b54af4c0ee3e4f02d8aefb088c97de02b57

      WEBCLIENT_CONNECT_TIMEOUT: 5000
      WEBCLIENT_READ_TIMEOUT: 10000

    depends_on:
      mysql:
        condition: service_healthy
    entrypoint: ["sh", "-c", "until nc -z mysql 3306; do echo waiting for mysql; sleep 2; done; java -jar /app/app.jar"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - backend

  mysql:
    image: mysql:8
    environment:

      MYSQL_DATABASE: distcalc_dev
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u admin -padmin || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 20
    restart: always

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    networks:
      - backend

  grafana:
    image: grafana/grafana
    volumes:
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3001:3000"
    networks:
      - backend

volumes:
  mysql-data:

networks:
  backend:
