version: '3.8'

services:
  geodistance:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"  # наружу и внутрь 8081
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - mysql
    networks:
      - backend

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_DATABASE: distcalc
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - backend

  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    networks:
      - backend

volumes:
  mysql-data:

networks:
  backend:
