server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  profiles:
    active: dev


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: INFO
    ru.ildar.distcalc: INFO

app:
  yandex:
    api-key: a95f5d4d-151b-42d9-8519-7aef29a5a5c1
    url: https://geocode-maps.yandex.ru/1.x
  dadata:
    api-key: 3ae49eb03d50473ad14419fe4dbd953a99dff432
    token: 3ae49eb03d50473ad14419fe4dbd953a99dff432
    secret: 37b92b54af4c0ee3e4f02d8aefb088c97de02b57
    url: https://cleaner.dadata.ru/api/v1/clean/address

webclient:
  connect-timeout-ms: 5000
  read-timeout-ms: 10000