spring:
  datasource:
    url: jdbc:mysql://mysql:3306/${MYSQL_DB}?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: INFO
    ru.ildar.distcalc: INFO
