spring:
  datasource:
    url: jdbc:mysql://localhost:3306/distcalc_dev?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: admin
    password: admin

logging:
  level:
    root: INFO
    ru.ildar.distcalc: INFO