spring:
  datasource:
    url: jdbc:mysql://mysql-prod-server:3306/distcalc?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: prod_user
    password: prod_password

logging:
  level:
    root: INFO
    ru.ildar.distcalc: INFO
