spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_DB}?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&autoReconnect=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    hikari:
      connection-timeout: 60000
      initialization-fail-timeout: 60000
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: INFO
    ru.ildar.distcalc: INFO
